eclipse/codewind-eclipse

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
> Issue #11: Change Add Project menu items to Add Existing Project

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectSelectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
Move the project type selection above the language selection.  Only show language selection for generic Docker projects.
> Issue #15: When adding an existing project, the project type should be selected first

- CONTRIBUTING.md
> Editing the Contributing file

- README.md
> Grammatical edits for the README.md file

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectWizard.java
Fixes https://github.com/eclipse/codewind-eclipse/issues/37
Checks to see if Codewind is installed or else downloads the images from dockerhub
> codewind installer

- dev/org.eclipse.codewind.base/feature.xml
- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.test/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.ui/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind/feature.xml
Fixes #42 
Update the version to 0.2 and update the plugin versions as needed.
> Issue #42: Update the version to 0.2

- dev/org.eclipse.codewind.core/.classpath
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindApplicationActionProvider.java
Fixes #33 
Remove validation features that are not working:
- Remove manual validation
- Remove quick fixes
> Issue #33: Remove validation features that are not working

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/ProjectType.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Fixes #13
Add a refresh button to the application overview page.  Also change docker project type name to "Other".
> Issue #13: Add refresh button to the application overview page

- README.md
> Minor grammatical edits

- dev/buildAll.gradle
> Download filewatcher plugins during build

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/BindProjectAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
Checks if Codewind is installed when adding existing project to Codewind if not, prompt user to install Codewind.
Signed-off-by: laven-s <laven.s@ibm.com>
> check codewind status for binding project

- Jenkinsfile
> Issue #82: Updating download area path

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
Fixes #76 
Use a CheckboxTableViewer instead of a Table with checkbox style as it appears to work better on Linux.
> Issue #76: Fix the project selection page on Linux

- dev/ant_build/build-cw.xml
- dev/ant_build/cw_imports.xml
> Issue #87: Fix build image name

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindManager.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Fixes #91 
Fix problem reloading the application overview page when Eclipse is restarted.
> Issue #91: Fix problem reloading application overview page on Eclipse restart

- README.md
> sishida-termchanges

- dev/org.eclipse.codewind.ui/plugin.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
Remove New from new wizard labels.  Also fixed up the dialogs to match the other dialogs used by Codewind.
> Issue #48: Remove New from new wizard labels

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/HttpUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
Fixes #104 
Increase the read timeout for project create and bind requests.
> Issue #104: Increase read timeout for create and bind requests

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallUtil.java
Fixes #94 
- Updated the installer
- Added support for versions with 0.2 as the default
> Issue #94: Update the installer and add support for versions

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/ProjectType.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
Fixed #121 
The project type selection page needs to support extensions so that extension projects can be properly added to Codewind.
> Issue #121: Add support for extensions to the project type selection page

- Jenkinsfile
fixes #127 
Signed-off-by: Joseph Kim kjoseph@ca.ibm.com
> Issue #127: Create 'latest' folder to store the latest build

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
Fixes #132 
Get the port changes on a project settings update event.
> Issue #132: Get the port changes on a project settings update event

- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseDebugTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseTest.java
Fixes #141 
- Update how the tests get the local connection
- Remove the code to build on Windows since auto build is now supported on Windows
- Add code to refresh the project after a file has been changed
> Issue #141: Various changes to get the test cases working again

- Jenkinsfile
> Issue #144: Add repository for the latest build

- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/Filewatcher.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/ProjectToWatch.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/DebugTimer.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/FileChangeEventBatchUtil.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/HttpGetStatusThread.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/HttpPostOutputQueue.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/WebSocketManagerThread.java
- dev/org.eclipse.codewind.filewatchers.eclipse/src/org/eclipse/codewind/filewatchers/eclipse/EclipseResourceWatchService.java
Port new comments from Go/TypeScript back to Java, and add a few missing 'final's.
> Add comments and minor code cleanup

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
Fixes #163 
Update the installer and accept the new status codes.
> Issue #163: Update the installer and accept the new status codes

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/ConnectionEnv.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindApplicationActionProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenTektonDashboardAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Fixes #185 
Add an action for opening the Tekton dashboard.
> Issue #185: Add an action for opening the Tekton dashboard

- dev/org.eclipse.codewind.test/resources/appsodyJavaMicroprofile/Hello.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AppsodyJavaMicroprofileAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AppsodyJavaSpringAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AppsodyNodeExpressAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/CodewindTestPlugin.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/GoAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/LagomAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/NodeAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/PythonAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/SpringAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/SpringDebugTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/util/CodewindUtil.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/util/TestUtil.java
Fixes #201 
Add auto build tests for other project types.
> Issue #201: Add auto build tests for other project types

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/ProjectType.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorLabelProvider.java
Fixes #217 
Update the code to handle extension project types.
> Issue #217: Fix the project type for extensions

- .gitignore
- dev/.gitignore
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/ContainerShellAction.java
Use bash if installed, else use sh
Signed-off-by: Tim Etchells <timetchells@ibm.com>
also add some things to gitignore
> Fix container shell when bash not installed

- README.md
Add development information for Codewind for Eclipse and Codewind images to the readme.
> Add development information to the readme

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/ProcessHelper.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseTest.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
Fixes #259 
Use the installer for project create and validate instead of the API.
> Issue #259: Use installer for project create and validate

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallUtil.java
- dev/org.eclipse.codewind/feature.xml
Fixes #264 
Update the installer to get the stop-all fix.  Also updated the versions.
> Issue #264: Update the installer to get the stop-all fix

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/CodewindCorePlugin.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/CodewindPrefsParentPage.java
Fixes #47 
Add preferences for Codewind installer timeouts.
> Issue #47: Add preferences for Codewind installer timeouts

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/JSONObjectResult.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/RepositoryInfo.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RepositoryManagementComposite.java
Fixes #271 
Add styles to the repository management composite.  Also commented out the description entry in the details since it is the same as what is in the table.
> Issue #271: Add styles to the repository management composite

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
Fixes #267 
Add support for HTTPS applications.
> Issue #267: Add support for HTTPS applications

- LICENSE
- NOTICE.md
> Update notice and license files

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/UnbindProjectAction.java
Fixes #285 
Don't delete the project contents until projectDeletion event is received.
> Issue #285: Don't delete project contents until projectDeletion event received

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindManager.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
Fixes #253
Check that Codewind is ready using the readiness API before creating the connection.
> Issue #253: Check for Codewind readiness before using APIs

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/IDEUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/CodewindPrefsParentPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RepositoryManagementComposite.java
Fixes #293 
Make the labels for repository details in the repository management dialog accessible.  Also fixed a couple of other minor issues.
> Issue #293: Make the repository details labels accessible

- dev/gradle.properties
Fixes #310 
Fix Eclipse download URL
> Issue #310: Fix eclipse download url

- Jenkinsfile
> Update Appsody to 0.4.4

- Jenkinsfile
> Pull installer from matching branch if it exists

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/BindProjectAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectSelectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
Fixes https://github.com/eclipse/codewind/issues/507
Allow the user to add projects from the file system without having to import them into Eclipse first.
> CW Issue #507: Allow the user to add projects from the file system

- README.md
Fixes https://github.com/eclipse/codewind/issues/474
> Recommend users install Eclipse 2019-09 to avoid bug 541220

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.base/feature.xml
- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.ui/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind/feature.xml
Update the version to 0.5.0.  Also update plugin versions.
> Update the version to 0.5.0

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectSelectionPage.java
Fixes https://github.com/eclipse/codewind/issues/530
Show a message for the workspace radio button if there are no available projects in the Eclipse workspace instead of showing an empty table.
> CW Issue #530: Show a message instead of an empty table if no projects

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindManager.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindObjectFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/AddConnectionAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindActionProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindConnectionActionProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RemoveConnectionAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindConnectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindConnectionWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectSelectionPage.java
Initial UI support for remote connections:
- Create connection action on Codewind element
- Remove connection action on Connection element (except for local)
- Project create support
- Project bind support
> Initial UI support for remote connections

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RepositoryManagementComposite.java
Pass in the repo name now that https://github.com/eclipse/codewind/pull/602 has been merged.
> CW Issue #541: Pass in the repo name now that the API accepts it

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallStatus.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Fixes #341 
The version specified by the CW_TAG environment variable should override any installed version.
> Issue #341: CW_TAG version should override any installed version

- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AppsodyJavaMicroprofileAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AppsodyJavaSpringAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AppsodyNodeExpressAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseTest.java
Fixes #343 
The appsody test cases need updating because of changes to Appsody templates.
> Issue #343: Required test case changes because of Appsody template changes

- Jenkinsfile
> Update appsody version to 0.4.6

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallUtil.java
Fixes #349 
Update the default install version to 0.5.0.
> Issue #349: Update the default install version to 0.5.0

- NOTICE.md
> Update Notices file for 0.5.0 in master branch

- NOTICE.md
Eclipse IDE PR for eclipse/codewind#649
Hide the CW settings edit and info buttons if the file does not exist.
> CW Issue #649: Hide CW settings button if the file does not exist

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallUtil.java
The CLI has changed to require the create option for a project create:
```
OLD: cwctl project <path> --url <url>
NEW: cwctl project create <path> --url <url>
```
> Support create option for cwctl: cwctl project create <path> --url <url>

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- Hook up the file watcher
- Fix up the project location (use locOnDisk)
> Hybrid: Hook up the file watcher

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/BindProjectAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectDeployedDialog.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
Prompt if the user is adding a project to connection B but the project is already deployed and enabled on connection A.  User can remove, disable or leave the project as is on connection A.
> Hybrid: Prompt if adding project that is already deployed on another connection

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/CodewindConnectionComposite.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindConnectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindConnectionWizard.java
Create a connection composite that can be used in the create wizard and later on in a dialog to edit the connection.
> Hybrid: Create a connection composite to use for create and edit

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindManager.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
Fixes https://github.com/eclipse/codewind/issues/799
Connect local Codewind if it is installed and running.
> CW Issue #799: Connect local Codewind at startup if installed and running

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/UIConstants.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RepositoryManagementComposite.java
Organize documentation links so it is easier to find the pages that the IDE depends on.
> Organize documentation links

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorLabelProvider.java
Hide the application status if it is unknown.
> CW Issue #831: Hide application status if unknown

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/ConnectionEnv.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/JSONObjectResult.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenTektonDashboardAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Support opening Tekton dashboard for remote projects.
> CW Issue #813: support opening Tekton dashboard for remote projects

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/CLIUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/TemplateUtil.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseTest.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/ManageReposAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/NewProjectAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RepositoryManagementComposite.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
Use the command line for managing template sources.
> CW Issue #841: Switch to cwctl for template source management

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallStatus.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Upgrade the old codewind workspace when updating the images.  Also removed some old version pattern matching.
> CW Issue #864: Upgrade the old codewind workspace when updating the images

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
Move the workspace upgrade after the install and start of the new version.
> CW Issue #864: The workspace upgrade should come after Codewind is installed

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindActionProvider.java
> Disable hybrid for 0.6.0

- README.md
> Update readme for 0.6.0

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallUtil.java
> Prevent socket exceptions when stopping Codewind

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/ProjectLanguage.java
Doing the simple fix for now.  Opened another issue to improve how languages and types are handled: https://github.com/eclipse/codewind/issues/1094.
> CW Issue #1093: Add bash to the project languages

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/AuthUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/CLIUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ConnectionUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ProjectUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/TemplateUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/LocalConnection.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindActionProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/ManageReposAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RepositoryManagementComposite.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorDropAssistant.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
- pass the connection id to cwctl commands that require it
- re-enabled the new connection action
- make sure global options specified first
> CW Issue #839: Pass the connection id to cwctl commands that require it

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectWizard.java
Extend WizardNewProjectCreationPage to get its existing location validation.
> CW Issue #995: Improve project location validation

- Jenkinsfile
For https://github.com/eclipse/codewind/issues/1145
> set appsody ver to 0.5.0

- README.md
PR for https://github.com/eclipse/codewind/issues/1146.
> Clarifying necessary Docker version

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/HttpUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ConnectionUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/CodewindConnectionComposite.java
Add support for authenticated socket.
> CW Issue #839: Add support for socket authentication

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/CodewindConnectionComposite.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/CompositeContainer.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindConnectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/RegistryComposite.java
Move the registry widgets to a separate composite.
> CW Issue #839: Move registry widgets to a separate composite

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallUtil.java
- dev/org.eclipse.codewind/feature.xml
Update versions and default install tag for 0.6.1
> Update versions and default install tag for 0.6.1

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectPage.java
Fixes https://github.com/eclipse/codewind/issues/1318
Use TableColumnLayout so the columns resize as the table is resized.
> CW Issue #1318: Make template table columns resize as the table resizes

- Jenkinsfile
For https://github.com/eclipse/codewind/issues/1343
> Bump appsody version to 0.5.1

- Jenkinsfile
For https://github.com/eclipse/codewind/issues/1343
(sorry, they released a quick fix)
> bump to 052

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.base/feature.xml
- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.eclipse/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.standalonenio/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.test/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.ui/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind/feature.xml
Update the versions for the 0.7.0 release
> Update the versions for the 0.7.0 release

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/AuthToken.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/AuthManager.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/JSONObjectResult.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/LocalConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/RegistryInfo.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/RemoteConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/console/SocketConsole.java
Refresh the authorization token as needed.
> CW Issue #839: Refresh the authorization token as needed

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
Accept the new detailed app status.  See https://github.com/eclipse/codewind/pull/1334 for details.
> CW Issue #1297: Accept the new detailed app status format

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/HttpUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
Fixes https://github.com/eclipse/codewind/issues/1370
Add a HostnameVerifier on the http connection and on the socket.
> CW Issue #1370: Add a HostnameVerifier on http connection and on the socket

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/ImagePushRegistryInfo.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/ManageRegistriesAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RegistryManagementComposite.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RegistryManagementDialog.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectSelectionPage.java
Update the calls to the registry API based on the changes to PFE for https://github.com/eclipse/codewind/issues/1300.
> CW Issue #1300: React to registry API changes

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/LocalConnectionActionProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectSelectionPage.java
Disable registry management for local connection since currently the registries are not preserved.  Users can log in from their machine as a work around.
> CW Issue #1178: Disable registry management for local connection

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/AuthManager.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/RemoteConnection.java
Pass an IAuthTokenProvider to the file watcher.
> CW Issue #1309: Pass an IAuthTokenProvider to the file watcher

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/CodewindCorePlugin.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CoreUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/CLIUtil.java
Put the CLI binares in `<home dir>/.codewind/<version>`.
> CW Issue #1295: Put the CLI binaries in <home dir>/.codewind/<version>

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/HttpUtil.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/HttpUtil.java
When creating the SSLContext, the TLS version should be TLSv1.2.
> CW Issue #1417: Fix the TLS version

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallUtil.java
Set the default install version to 0.7.0.
> Set the default install version to 0.7.0

- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/Filewatcher.java
Parent issue: https://github.com/eclipse/codewind/issues/1434
> CW Issue #1434 - PUT request should not be doing cert/host-checking

- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/CLIState.java
Parent issue: https://github.com/eclipse/codewind/issues/1411
> CW Issue #1411 - Call project sync with --insecure by default 

- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/CLIState.java
Parent issue: https://github.com/eclipse/codewind/issues/1411
> CW Issue #1411 - Call project sync with --insecure by default

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RepositoryManagementComposite.java
Fix the shell title for the add template source dialog.
> CW Issue #787:Fix shell title for add a template source dialog

- dev/org.eclipse.codewind.filewatchers.eclipse/src/org/eclipse/codewind/filewatchers/eclipse/CodewindResourceChangeListener.java
Parent issue: https://github.com/eclipse/codewind/issues/1487
> CW Issue #1487 - NPE in Eclipse file watcher for removed resource

- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/WebSocketManagerThread.java
Parent issue: https://github.com/eclipse/codewind/issues/1498
> [Eclipse IDE] Filewatcher unable to connect to remote PFE via WebSockets, when using IBM JVM

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
Related issue is https://github.com/eclipse/codewind/issues/1179
> Disable socket.io read timeout

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/UIConstants.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/CodewindConnectionComposite.java
Updated the link for image registries.
Added a link for remote setup to the new connetion page
> Update doc links for registries and remote connections

- dev/org.eclipse.codewind.core/binaries/meta-pull.sh
React to change made in https://github.com/eclipse/codewind-vscode/pull/367
> React to vscode rename of dev/bin/README.txt

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/AuthUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/CLIUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ConnectionUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ProjectUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/TemplateUtil.java
Fixes https://github.com/eclipse/codewind/issues/1007
- Passing JSON flag as global option now
- Consolidated various commands
- Did not add JSON for all commands as it is not supported by all of them.  Can do this later once the CLI is cleaned up.
> CW Issue #1007: Pass json flag as global option, clean up commands

- Jenkinsfile
Update the appsody release to 0.5.4.
> Update the appsody release to 0.5.4

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/CodewindCorePlugin.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallUtil.java
Update the default install version and CLI location for 0.8.0.
> Update the default install version and CLI location for 0.8.0

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectPage.java
- The table in the new project dialog is much better now
- Could not get the entries to match the background in the overview page but they are grey now instead of white.  Other form editors such as the server editor have the same issue in dark mode.
> CW Issue #732: Fix white backgrounds in dark mode

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ProjectUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/util/CodewindUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/UnbindProjectAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorDropAssistant.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
Use CLI for project remove instead of the REST API.
> CW Issue #1565: Use CLI for project remove

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
- Use the detected type if the validation page is active otherwise use the type from the project type page
- In the project type selection page, update the project type and subtype as the user makes selections rather than trying to retrieve the selection later when the widgets could be disposed
- Add null checks for projectInfo in the project type selection page
> CW Issue #1771: Fix NPE in BindProjectWizard

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallUtil.java
Don't use the progress monitor if it is canceled.
> CW Issue #873: Don't use the progress monitor if it is canceled

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/UIConstants.java
Fix the remote connection composite learn more link URL
> CW Issue #1817: Fix the remote connection composite learn more link URL

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
fixes https://github.com/eclipse/codewind/issues/1520
tested with Application Monitor and Performance dashboard on local and remote
Signed-off-by: Richard Waller <Richard.Waller@ibm.com>
> fix: use correct url for open app monitor

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
> CW Issue #1520: use the appBaseURL for remote metrics

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/ConnectionEnv.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindApplicationActionProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenTektonDashboardAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RemoteConnectionActionProvider.java
Add scheme to the tekton url and put the action on the connection instead of the application.
> CW Issue #1845: Add scheme to tekton url and put action on the connection

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/ConnectionEnv.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindApplicationActionProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenTektonDashboardAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RemoteConnectionActionProvider.java
Add the scheme to the tekton dashboard url and put the action on the connection instead of the application.
> CW Issue #1845: Add scheme to tekton url and move action to the connection

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnectionManager.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AppsodyJavaMicroprofileAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseDebugTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseValidationTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/NodeAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/NodeValidationTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/util/CodewindUtil.java
Fixes #549 
Update the tests based on recent code changes.
> Issue #549: Update tests based on recent code changes

- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/Filewatcher.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/ProjectToWatch.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/CLIState.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/IndividualFileWatchService.java
- dev/org.eclipse.codewind.filewatchers.standalonenio/src/org/eclipse/codewind/filewatchers/Main.java
Link to parent issue: https://github.com/eclipse/codewind/issues/1399
Testing:
- Automated Filewatcherd tests all passing (both normal and chaos engineering versions)
- Manual test of the changes in self-hosted Eclipse to ensure no new issues were introduced
- Tested and verified that this change can go in safely without Andrew's corresponding PFE change (linked on 1399)
> CW Issue 1399: Project sync support for reference to files outside of project folder

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CoreUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/CLIUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/OtherUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ProjectUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/TemplateUtil.java
Fixes https://github.com/eclipse/codewind/issues/1938
Common up the code for checking the result of cwctl commands.
> CW Issue #1938: Improve handling of errors from cwctl commands

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
Log project watch status changed failures.  When a path is included in the JSON object for the event then a message dialog can be shown to the user with an error like:
Codewind was unable to scan the project folder '(path)' for changes, which means auto-build will not trigger when a source code file is modified. Ensure that the directory exists, and that the user running the IDE has appropriate read/write permissions for this folder.
> CW Issue #1751: log project watch status changed failures

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.base/feature.xml
- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.eclipse/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.standalonenio/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.test/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.ui/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind/feature.xml
Update the versions for the 0.9.0 release. Updated the third digit since there are only bug fixes going in to this release.
> CW Issue #1967: update versions for the 0.9.0 release

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CoreUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
Add in the link for app status notify messages.
> CW Issue #1812: add link for app status notify messages

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/NewProjectAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectWizard.java
Fixes https://github.com/eclipse/codewind/issues/2014
Add a select connection page to the wizard for File > New > Codewind Project when there is more than one connection.
> CW Issue #2014: Add select connection page to new project wizard

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallUtil.java
Update the default install version to 0.9.0
> Update the default install version to 0.9.0

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectValidationPage.java
Move the test for the connection type into the page update code.
> CW Issue #2065: Move test for connection type into page update code

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/CodewindCorePlugin.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallUtil.java
- dev/org.eclipse.codewind/feature.xml
Signed-off-by: Toby Corbin <corbint@uk.ibm.com>
> raise versions to 0.8.1 for ifix

- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
Use the notification id to only show notifications once.
> CW Issue #1812: Use the notification id to only show notifications once

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/ProjectLanguage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/EnableDisableInjectMetricsAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenAppMonitorAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenPerfMonitorAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Use the new streamlined metrics injection and metrics and perf dashboard information in the project listing.  See https://github.com/eclipse/codewind/issues/1815#issuecomment-583354048 for details.
> CW Issue #1815: Use new dashboard information in project listing

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/ProjectLanguage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/EnableDisableInjectMetricsAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenAppMonitorAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenPerfMonitorAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Use the new streamlined metrics injection and metrics and perf dashboard information in the project listing. See eclipse/codewind#1815 (comment) for details.
Also renamed `Application Monitor` action to `Metrics Dashboard`.
> CW Issue #1815: Use new dashboard information in project listing 090

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/CLIUtil.java
Fixes https://github.com/eclipse/codewind/issues/2155
Log output from cwctl if logging is enabled.
> CW Issue #2155: Log output from cwctl if logging enabled

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/UIConstants.java
The project settings doc link needs to be changed for the new restructured documentation.
> CW Issue #2187: Fix project settings doc link 090

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/EnableDisableInjectMetricsAction.java
Restore the inject metrics action on apps with embedded metrics.
> CW Issue #2213: Restore the inject metrics option on apps with embedded metrics 0.9.0

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/EnableDisableInjectMetricsAction.java
Restore the inject metrics action on apps with embedded metrics.
> CW Issue #2213: Restore the inject metrics option on apps with embedded metrics

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.base/feature.xml
- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.eclipse/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.standalonenio/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.test/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.ui/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind/feature.xml
Fixes https://github.com/eclipse/codewind/issues/2325
Update the plugin and feature versions for 0.10.0.
> CW Issue #2325: Update plugin and feature versions for 0.10.0

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/UIConstants.java
Fix the doc link for image registries.
> CW Issue #2382: Fix the doc link for image registries

- Jenkinsfile
Update the appsody version to 0.5.9
> CW Issue #2378: Update the appsody version to 0.5.9

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallUtil.java
Update the default install version to 0.10.0
> Update the default install version to 0.10.0

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/UIConstants.java
We now have a file for adding an image registry in remote Codewind. This is a PR to update the link.
> Updating link to remote documentation

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/LocalConnection.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorLabelProvider.java
Fixes https://github.com/eclipse/codewind/issues/2422
- Update the install status if the local connection is lost
- In the label provider, if the install status is started/running then check if connected and show error if not
> CW Issue #2422: Fix status if Codewind stopped

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorLabelProvider.java
Hide the build status if it is unknown.
> CW Issue #2052: Hide build status if unknown

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/ConnectDisconnectAction.java
Missing call to UpdateHandler on connection disconnection action
> CW Issue #2424: Missing UpdateHandler call on connection disconnect action

- dev/ant_build/build-cw.xml
- dev/ant_build/cw_test_imports.xml
- dev/org.eclipse.codewind.core/build.properties
- dev/org.eclipse.codewind.test.feature/.project
- dev/org.eclipse.codewind.test.feature/build.properties
- dev/org.eclipse.codewind.test.feature/build.xml
- dev/org.eclipse.codewind.test.feature/feature.properties
- dev/org.eclipse.codewind.test.feature/feature.xml
- dev/org.eclipse.codewind.test.feature/license.html
- dev/org.eclipse.codewind.test/.classpath
- dev/org.eclipse.codewind.test/build.xml
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AllTests.java
- dev/org.eclipse.codewind.ui/build.properties
Generates an install zip for the test plugins and features.
https://github.com/eclipse/codewind/issues/2471
No
No
> CW Issue #2471: Generate an install zip for test plugins and features

- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/PathUtils.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/FileChangeEventBatchUtil.java
- dev/org.eclipse.codewind.filewatchers.standalonenio/src/org/eclipse/codewind/filewatchers/JavaNioWatchService.java
Detect and report deletion of project root
Parent issue: eclipse/codewind#2278
> CW Issue #2169: Codewind should react to a project being deleted from disk

- dev/Dockerfile
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/CLIUtil.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AllTests.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseTest.java
- dev/run.sh
- dev/runTest.sh
Creates a Dockerfile and scripts so that tests can be run automatically in Docker.
https://github.com/eclipse/codewind/issues/2480
No
No
> CW Issue #2480: Set up automated testing

- Jenkinsfile
- dev/ant_build/cw_test_imports.xml
- dev/run.sh
Renames the test zip file so there is no conflict with the product zip file.
https://github.com/eclipse/codewind/issues/2496
No
No
> CW Issue #2496: Change the test zip name so there is no conflict

- Jenkinsfile
Add the JUnit test run to the Jenkinsfile.
> Add the test run to Jenkinsfile

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.base/feature.xml
- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.eclipse/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.standalonenio/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.test/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.ui/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind/feature.xml
Update the feature and plugin versions for the 0.11.0 release
https://github.com/eclipse/codewind/issues/2500
No
No
> CW Issue #2500: Update versions for 0.11.0

- Jenkinsfile
> Add a build timeout

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
Add comments to the project type selection code to try and make it more clear how it works.
https://github.com/eclipse/codewind/issues/1833
No
The original plan was to separate the concepts of language and subtype but they are overloaded in the project-types api so it did not make sense to separate them in the code (might make it even more confusing). Instead I just added some comments and did some refactoring.
> CW Issue #1833: Add comments to project type selection code

- Jenkinsfile
Runs the JUnit tests with the build
https://github.com/eclipse/codewind/issues/2502
No
This change was tested on the runJUnitTests branch. Link to a successful build with this change: https://ci.eclipse.org/codewind/job/Codewind/job/codewind-eclipse/job/runJUnitTests/2/. Associated test report: https://ci.eclipse.org/codewind/job/Codewind/job/codewind-eclipse/job/runJUnitTests/2/testReport/. Currently only one test case is included in the tests list. Others will be added in a separate PR.
> CW Issue #2502: Add JUnit tests to the build

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RemoveConnectionAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Adds code to display a confirmation dialog on connection remove.
https://github.com/eclipse/codewind/issues/2510
No
No
> CW Issue #2510: Show a confirmation dialog on connection remove

- Jenkinsfile
Comment out the JUnit tests in the Jenkinsfile
Unfixes https://github.com/eclipse/codewind/issues/2502
No
No
> CW Issue 2502: Remove JUnit tests from build

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/RegistryUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/LocalConnectionActionProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/ManageRegistriesAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RegistryManagementComposite.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RegistryManagementDialog.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectValidationPage.java
Supports registries for the local connection. Only pull registries can be specified for the local connection.
https://github.com/eclipse/codewind/issues/1306
Yes
No
> CW Issue #1306: Support registries for local connection

- dev/org.eclipse.codewind.filewatchers.standalonenio/run_fwd_tests_if_needed.sh
https://github.com/eclipse/codewind/issues/2494
> CW Issue #2494 - Eclipse non-PR builds will output an (ignored) error in filewatcher tests

- Jenkinsfile
- dev/run.sh
> Change the ownership of the test codes after unzip to be able to cleanup workspace

- dev/run.sh
> Change the ownership of the test codes

- dev/Dockerfile
> Install dbus and dbus-x11 for SWTBot

- dev/Dockerfile
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/util/CodewindUtil.java
- Installs missing SWTBot dependencies
- Checks for null connection in test cleanup code
https://github.com/eclipse/codewind/issues/2541
No
No
> CW Issue #2541: Fix problems with the automated tests

- dev/Dockerfile
> Fix JUnit test runs

- Jenkinsfile
> Disable JUnit tests

- Jenkinsfile
Disable the JUnit tests in the build and continue to investigate/resolve on the junitsInBuild branch.
> Disable the JUnit tests in the build

- dev/runTest.sh
> Set INSECURE_KEYRING to true

- Jenkinsfile
> Re-enable JUnit tests

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/GetStartedAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/WelcomePageEditorPart.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/ViewHelper.java
Fix accessibility problems with the Codewind welcome page.
https://github.com/eclipse/codewind/issues/2538
No
No
> CW Issue #2538: Fix accessibility for Codewind welcome page

- Jenkinsfile
- dev/run.sh
- dev/runTest.sh
> Set up tests in build

- dev/run.sh
> Fixes to run.sh

- dev/run.sh
> Fix the if statement

- dev/runTest.sh
> Fix the home directory for eclipse

- dev/runTest.sh
> Fix directory for JUnit results

- dev/run.sh
> Exit on error for initial test setup

- dev/run.sh
- dev/runTest.sh
> Add comments to test scripts

- dev/run.sh
> Install docker-compose if necessary

- dev/run.sh
> Switch to using command instead of which

- dev/run.sh
> Move set -e after the docker-compose check

- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/GoAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/NodeAutoBuildTest.java
Adds the following to the test cases:
- Check the dashboards (if available)
- Disable project and check that it is disabled and can't be pinged and the consoles are closed
- Enable project check that it is enabled and goes to running state (as well as regular checks to ping the project and check the consoles)
- Remove project and check that it is removed and can't be pinged and the consoles are closed
- Add existing project and check that the detected type is correct (as well as regular checks to ping the project and check the consoles)
https://github.com/eclipse/codewind/issues/2558
No
No
> CW Issue #2558: Improve the test cases

- dev/run.sh
> Fix adding docker-compose to the path

- Jenkinsfile
> Clean up containers when tests are finished

- Jenkinsfile
> Remove containers when tests are done

- Jenkinsfile
> Add comment before removing containers

- Jenkinsfile
Cleans up the docker containers after the tests are run.
https://github.com/eclipse/codewind/issues/2579
No
Better version of PR #677
> CW Issue #2579: Clean up containers after tests are run

- Jenkinsfile
Bump appsody to 0.6.0
https://github.com/eclipse/codewind/issues/2557
> Bump appsody to 0.6.0

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallUtil.java
Updates the default install version to 0.11.0
> Update the default install version to 0.11.0

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/console/CodewindConsoleFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/ContainerShellAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Adds the connection name to the container shell and console log titles.
https://github.com/eclipse/codewind/issues/2600
No
No
> CW Issue #2600: Add connection name to view titles

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.base/feature.xml
- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.eclipse/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.standalonenio/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.test/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.ui/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind/feature.xml
Updates the plugin and feature versions for 0.12.0.
https://github.com/eclipse/codewind/issues/2626
No
No
> CW Issue #2626: Bump up versions for 0.12.0

- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AllTests.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AppsodyJavaMicroprofileAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AppsodyJavaSpringAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AppsodyNodeExpressAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseAppsodyAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseDebugTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/GoAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/LagomAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/LibertyDebugTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/NodeAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/PythonAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/SpringAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/SpringDebugTest.java
- Fixes a problem with static variables when running tests in a group
- Adds more logging as tests run
- Adds more tests to the test list run with the build.
https://github.com/eclipse/codewind/issues/2545
No
No
> CW Issue #2545: Add more tests to the build

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ProjectUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorDropAssistant.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectWizard.java
Attempts to clean up if project create or bind times out or is canceled.
https://github.com/eclipse/codewind/issues/2601
No
No
> CW Issue #2601: Clean up if project create or bind times out or is canceled

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CoreUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/KubeUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/ContainerShellAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Adds support for opening a shell into the container for remote applications.
https://github.com/eclipse/codewind/issues/822
No
Tested on Windows and Linux. Don't currently have access to a MAC.
> CW Issue #822: Support container shell for remote

- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BuildVerificationTests.java
- dev/runTest.sh
> Reorganize the test lists

- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BuildVerificationTests.java
- dev/runTest.sh
Create a separate build test list as running all of the tests as part of the build would take too long.
- AllTests - all of the tests
- BuildVerificationTests - subset of the tests to run with the build
https://github.com/eclipse/codewind/issues/2649
No
No
> Reorganize test lists so there is a separate list for the build

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindConnectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectValidationPage.java
- Fix the background for the new connection page on Linux
- Fix the spacing for the project validation page on Linux
https://github.com/eclipse/codewind/issues/2645
No
No
> CW Issue #2645: Fix the new connection composite background on Linux

- README.md
Adds information about the automated tests to the readme.
https://github.com/eclipse/codewind/issues/2649
No
No
> CW Issue #2649: Add test information to the readme

- Jenkinsfile
- dev/org.eclipse.codewind.core/build.properties
- dev/org.eclipse.codewind.core/resources/install-version.properties
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/CLIUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/set-install-version.sh
Set the install version based on the build branch.
> CW Issue #2672: Set the install version based on the build branch

- Jenkinsfile
Fix install version properties file path in Jenkinsfile
> CW2672: Fix install version properties file path in Jenkinsfile

- dev/runTest.sh
Puts the eclipse workspace for the tests in the build workspace so it gets cleaned up
https://github.com/eclipse/codewind/issues/2678
No
No
> CW Issue #2678: Put the eclipse workspace for the tests in the build workspace

- Jenkinsfile
Publish builds to archive site instead of download site
https://github.com/eclipse/codewind/issues/2700
No
> Publish builds to archive site instead of download site

- dev/org.eclipse.codewind.core/plugin.properties
- dev/org.eclipse.codewind.core/plugin.xml
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/CodewindCorePlugin.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindObjectFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/KubeUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/RemoteEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/CLIUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ProjectUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/StartMode.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/launch/CodewindLaunchConfigDelegate.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/launch/CodewindLaunchListener.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/launch/UtilityLaunchConfigDelegate.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseTest.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/IDEUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/AttachDebuggerAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/ContainerShellAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RestartDebugModeAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RestartRunModeAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/debug/NodeJSDebugLauncher.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Adds debug support for applications deployed on remote connections.
https://github.com/eclipse/codewind/issues/1990
Yes
No
> CW Issue #1990: Support remote debug

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RepositoryManagementComposite.java
Fixes how changes are detected in the template source list.
https://github.com/eclipse/codewind/issues/1597
No
No
> CW Issue #1597: Fix how changes are detected in the repo list

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/RemoteEclipseApplication.java
Add more logging around forwarding the debug port
https://github.com/eclipse/codewind/issues/1990
No
No
> CW Issue #1990: Add more logging around forwarding the debug port

- Jenkinsfile
Bump appsody to version 0.6.1
https://github.com/eclipse/codewind/issues/2764
No
> appsody 0.6.1

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/CodewindPrefsParentPage.java
- Update all of the preferences to their defaults if the user clicks the Restore Defaults button
- Don't apply any preferences until the user clicks Apply
https://github.com/eclipse/codewind/issues/2836
No
No
> CW Issue #2836: Fix restore defaults for the Codewind preference page

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindManager.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnectionManager.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RefreshAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
https://github.com/eclipse/codewind/issues/2832
No
No
> CW Issue #2832: Support refreshing the connections

- dev/org.eclipse.codewind.core/updateBinaries.launch
- dev/org.eclipse.codewind.core/updateBinaries.xml
Adds a build file and launch to update the binaries (cwctl and appsody) automatically.
https://github.com/eclipse/codewind/issues/2846
No
Please test on MAC
> CW Issue #2846: Create a build file and a launch to update the binaries

- dev/org.eclipse.codewind.filewatchers.standalonenio/src/org/eclipse/codewind/filewatchers/JavaNioWatchService.java
Parent issue https://github.com/eclipse/codewind/issues/2726
> CW Issue #2726 - [Filewatcherd] Event loop exception in WatchedPath

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/CodewindCorePlugin.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnectionManager.java
Saves and restores the connection state for remote connections so the state is maintained if Eclipse is restarted.
https://github.com/eclipse/codewind/issues/2823
No
No
> CW Issue #2823: Save the connection state for remote connections

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/RemoteEclipseApplication.java
Makes sure the debugger reattaches after a build due to a file change.
https://github.com/eclipse/codewind/issues/2884
No
No
> CW Issue #2884: fix remote debug reattach

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.base/feature.xml
- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.eclipse/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.standalonenio/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.test/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.ui/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind/feature.xml
Updates the plugin and feature versions for the 0.13.0 release.
https://github.com/eclipse/codewind/issues/2920
No
No
> CW Issue #2920: Update plugin and feature versions for 0.13.0

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/CLIUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallStatus.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorLabelProvider.java
Remove old versions of cwctl/appsody when updating Codewind to a newer version.
https://github.com/eclipse/codewind/issues/2869
No
No
> CW Issue #2869: Remove old cwctl/appsody when updating Codewind to newer version

- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseAppsodyAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseAppsodyDebugTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseDebugTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseValidationTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/util/CodewindUtil.java
Modifies the test so that they can be run on a local or a remote connection.
https://github.com/eclipse/codewind/issues/2954
No
No
> CW Issue #2954: Modify tests so they can run with local or remote connection

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnectionManager.java
Fixes the initial status for the local connection by not adding it to the connection list until the install status is updated.
https://github.com/eclipse/codewind/issues/2963
No
No
> CW Issue #2963: Fix initial status for the local connection

- README.md
Update for issue https://github.com/eclipse/codewind/issues/2953.
Update the documentation to state the correct version.
https://github.com/eclipse/codewind/issues/2953
It is a documentation change. :)
> Updating Eclipse Version

- dev/org.eclipse.codewind.ui/plugin.xml
Adds a tab group to the remote launch configuration.
https://github.com/eclipse/codewind/issues/3007
No
No
> CW Issue #3007: Add tab group to remote launch config

- Jenkinsfile
Pickup appsody 0.6.2
For https://github.com/eclipse/codewind/issues/2995
> pickup appsody 0.6.2

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
Updates the pod name and base url if available on a project restart event.
https://github.com/eclipse/codewind/issues/3035
No
No
> CW Issue #3035: Update pod name and base url on restart

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/ExtensionConfig.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/debug/NodeJSDebugLauncher.java
Uses the extension config in the project info to get the container app root if available.
https://github.com/eclipse/codewind/issues/3044
No
No
> CW Issue #3044: Fix debug remote app root for appsody node projects

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/ExtensionConfig.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/debug/NodeJSDebugLauncher.java
Uses the extension config in the project info to get the container app root if available.
eclipse/codewind#3044
No
No
> CW Issue #3044: Fix debug remote app root for appsody node projects for 0.13.0

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Change any remaining messages with "Container Registries" to "Image Registries".
https://github.com/eclipse/codewind/issues/3046
No
No
> CW Issue #3046: Change instances of Container Registries to Image Registries

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Change any remaining messages with "Container Registries" to "Image Registries".
eclipse/codewind#3046
No
No
> CW Issue #3046: Change instances of Container Registries to Image Registries 0.13.0

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Positions the labels in the project overview page at the beginning. Still looking for a fix to the scrollbar problem so it will be in a separate PR.
https://github.com/eclipse/codewind/issues/3081
No
No
> CW Issue #3081: Position the project overview labels at beginning

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Fixes the scrollbars when the size of the content changes.
https://github.com/eclipse/codewind/issues/3081
No
No
> CW Issue #3081: Reflow when the size changes to fix up the scroll bars

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/OtherUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Fix up the diagnostics command to pass in collect: `cwctl diagnostics collect`. Also fixed a capitalization problem with the log level action.
https://github.com/eclipse/codewind/issues/3111
No
No
> CW Issue #3111: Add collect to diagnostics command

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/OtherUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Fix up the diagnostics command to pass in collect: `cwctl diagnostics collect`. Also fixed a capitalization problem with the log level action.
https://github.com/eclipse/codewind/issues/3111
No
No
> CW Issue #3111: Add collect to diagnostics command 0.13.0

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ProjectLinks.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ProjectUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnectionManager.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindApplicationActionProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/ManageLinksAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/UnbindProjectAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/LinkManagementComposite.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/LinkManagementDialog.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RegistryManagementDialog.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorLabelProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/UpdateHandler.java
Adds support for project linking.
https://github.com/eclipse/codewind/issues/2852
Yes
No
> CW Issue #2852: Support project linking

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/LinkManagementComposite.java
Minor improvements to project linking support:
- In add link dialog, select the first project in the list if there is one
- Make sure to refresh target projects on link add/edit/remove
https://github.com/eclipse/codewind/issues/2852
No
No
> CW Issue #2852: Minor improvements to project linking support

- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AppsodyOpenLibertyAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AppsodyOpenLibertyDebugTest.java
Fixes stability problems with Appsody Open Liberty tests.
https://github.com/eclipse/codewind/issues/3152
No
No
> CW Issue #3152: Fix stability problems with Appsody Open Liberty tests

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ProjectLinks.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/LinkManagementComposite.java
Handles projectLink events from the runtime:
- Makes sure the source and target app are up to date
- Shows any error to the user
https://github.com/eclipse/codewind/issues/2852
No
No
> CW Issue #2852: Handle project link events

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.base/feature.xml
- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.eclipse/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.standalonenio/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.test/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.ui/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind/feature.xml
Updates the plugin and feature versions for the 0.14.0 release.
https://github.com/eclipse/codewind/issues/3162
No
No
> CW Issue #3162: update versions for 0.14.0

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/UIConstants.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/WelcomePageEditorPart.java
Fixes the remote deploy link on the welcome page to point to the correct documentation page.
https://github.com/eclipse/codewind/issues/3187
No
No
> CW Issue #3187: fix incorrect remote deploy link

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/UIConstants.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/LinkManagementComposite.java
Fixes the learn more link on the project linking composite to point to the project linking documentation.
https://github.com/eclipse/codewind/issues/3170
No
No
> CW Issue #3170: Fix up the learn more link on the project linking composite

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/UIConstants.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/LinkManagementComposite.java
Fixes the learn more link on the project linking composite to point to the project linking documentation.
https://github.com/eclipse/codewind/issues/3170
No
No
> CW Issue #3170: Fix up the learn more link on the project linking composite 0.14.0

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.base/feature.xml
- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind/feature.xml
Update the versions for the 0.14.1 release
https://github.com/eclipse/codewind/issues/3206
No
No
> CW Issue #3206: Update versions for 0.14.1
