- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/LanguageSelectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectSelectionPage.java
Fixes #7 
- Detect the project type for the connection add project menu item
- Don't set the selected project until the user clicks next (so the type detection is only done once the user has made their final selection)
> Issue #7: Detect project type for connection add project menu item

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
There was a spot in the code where dispose was not being called on an application that was removed which was causing log consoles to be left around.  Move the dispose call into the removeApp method so that it always gets called when an app is removed.
> Issue #18: Make sure the application is disposed when it is removed

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/console/ProjectTemplateInfo.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectWizard.java
For project create, the project type is now in the template info.  Pass this in on the bind step instead of calculating it.
> Issue #34: For project create, get the project type from the template info

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectSelectionPage.java
If there is only one project in the add existing project selection page then select it automatically.
> Issue #32: Select project if only one in project selection page

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/CodewindCorePlugin.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/ProcessHelper.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/CodewindPrefsParentPage.java
Fixes #45
Allow the user to decide whether stopping Codewind also stops application containers:
- Added a preference with always, never and prompt choices - prompt is the default
- If preference is set to prompt a dialog shows asking the user if they want to delete application containers
- The dialog also has a checkbox to save the user's choice and don't show the dialog again (this will set the preference)
- Also fixed a problem with ProcessHelper where waitForProcess was not checking if the monitor was canceled
- Added monitor canceled checks in CodewindInstall after each step
> Issue #45: Add a stop application containers preference

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindManager.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RefreshAction.java
Fixes #53 
If there are no active applications then don't prompt the user to stop applications when stopping Codewind.  Also fixed a problem with refreshing the root Codewind element in the explorer view.
> Issue #53: Don't prompt on stop if there are no active apps

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Fixes #63
Removed the borders that were showing on the text fields in the application overview on Linux.  Also changed the Application URL text field to have the same style as other text fields since it was affecting the spacing on Linux.
> Issue #63: Remove borders on text fields in app overview (Linux)

- dev/org.eclipse.codewind.filewatchers.eclipse/src/org/eclipse/codewind/filewatchers/eclipse/CodewindResourceChangeListener.java
Signed-off-by: Jonathan West <jgwest@ca.ibm.com>
> Issue #81: Resource change listener should ignore non-file-change deltas

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Fixes #67
The application URL when it switches from being a hyperlink to just text was getting lost altogether on Linux.  Adding a call to layout on the form fixes the problem.
> Issue 67: Fix overview page application URL on Linux

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Fixes #98 
The application overview page should be showing the root url which includes the context root instead of the base url which does not.
> Issue #98: The application overview page should show the root URL

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/BindProjectAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindConnectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectPage.java
Fixes #106 
- Dump system out and system error when installer fails
- When uninstalling, always do a stop-all first since uninstall fails if user containers are running
> Issue #106: Dump system out and system error when installer fails

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenAppMonitorAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenPerfMonitorAction.java
Fixes #111 
The performance  and app monitor pages don't display in the internal web browser on Windows so force it to use the external web browser.
> Issue #111: Use the external browser for the perf and app monitor pages on Windows

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorLabelProvider.java
Fixes #117 
Use the JavaScript icon for generic Docker projects and extensions if the language is JavaScript.
Also, for extensions, base the icon on the language if available.
> Issue #117: Use the JavaScript icon for generic Docker projects and extensions

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenPerfMonitorAction.java
Fixes #19
The app monitor and performance monitor pages had the same id for a project. Make sure the ids are unique.
> Issue #19: Use unique ids for the app and perf monitor pages.

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/debug/NodeJsBrowserDialog.java
Fixes #124 
Use the Codewind home page as the default URL for Node.js debug.
> Issue #124: Use the Codewind home page as the default url for Node.js debug

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/ProjectLanguage.java
Update the root paths for application metrics to include a trailing /.
> Issue #136: Add trailing / to application metrics root

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CoreUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/IUpdateHandler.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnectionManager.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/UpdateHandler.java
Fixes #41 
If an application is removed then the overview page is already being cleaned up.  This PR fixes the case where the connection is removed (Codewind is stopped or uninstalled).
> Issue #41: Remove app overview pages when connection is removed

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Fixes #79 
If debug is not supported, instead of showing "Not available" for debug ports in the overview page, show "Debug not supported for this project type" instead.
> Issue #79: Show debug not supported for debug entries in overview as applicable

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
Fixes #134 
When application is updated check for "contextRoot" as well as the old "contextroot" in the json.  Remove the check for "custom": {"contextroot" as this is not used anymore.
> Issue #134: Check for contextRoot when updating application

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
Fixes #148 
Base debug support on the project language rather than the project type.
> Issue #148: Base debug on the project language instead of the project type

- dev/org.eclipse.codewind.ui/plugin.xml
Fixes #65 
To not use the describer of the base type it should set the describer attribute to the empty string rather than add the describer element and set its class attribute to the empty string.  However it is probably better to use the describer of the base type so removed the describer element and everything is working properly now.
> Issue #65: Don't add empty describer element for .cwsettings content type

- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/Filewatcher.java
- dev/org.eclipse.codewind.filewatchers.eclipse/src/org/eclipse/codewind/filewatchers/eclipse/CodewindFilewatcherdConnection.java
- dev/org.eclipse.codewind.filewatchers.eclipse/src/org/eclipse/codewind/filewatchers/eclipse/CodewindResourceChangeListener.java
- dev/org.eclipse.codewind.filewatchers.standalonenio/src/org/eclipse/codewind/filewatchers/JavaNioWatchService.java
Fix is to use `splitRelativeProjectPathIntoComponentPaths` to check the change path (which I was already using to solve this issue in the Eclipse filewatcher project)
> Ensure that path filters are applied to parent paths of a file change notification

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/UnbindProjectAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Fixes #129 
- Prompt user if they want to also delete the project contents when removing a project from Codewind, the default is not to delete the contents
- Support multiple selection for the Remove action
> Issue #129: Allow deletion of project contents on remove action

- dev/org.eclipse.codewind.ui/plugin.properties
- dev/org.eclipse.codewind.ui/plugin.xml
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectWizard.java
Fixes #28 
- Added a shortcut for the new Codewind project wizard.  This shows it in the Project Explorer view in the J2EE perspective if there are no projects yet.  It also puts it at the top level of the New Wizard menu for this perspective
- Added a shortcut for the Codewind Explorer view.  This puts it at the top level of the Window > Show View menu for the J2EE perspective so the user does not have to go to Other.
- Fixed a bug where if Codewind was not installed when the wizard is being launched it would try to close Eclipse
> Issue #28: Add a shortcut for the new Codewind project wizard

- dev/org.eclipse.codewind.ui/plugin.xml
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindApplicationActionProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RestartDebugModeAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RestartRunModeAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RootActionProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Fixes #80 
Only show the restart actions that are valid for the project type.  The toolbar restart actions will show all of the time but will be disabled if not supported by the project.
> Issue #80: Don't show restart actions if not supported for the project type

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/AppStatus.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseDebugTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/NodeValidationTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/util/CodewindUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/AttachDebuggerAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenAppAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenAppMonitorAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenPerfMonitorAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RestartDebugModeAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RestartRunModeAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorLabelProvider.java
Fixes #135 
- Allow open app, open app monitor and open perf monitor actions when the application is in starting state
- Add description for the application when available
- Refactor AppState to AppStatus to be consistent with the API
> Issue #135: Allow open actions when app is in starting state

- dev/org.eclipse.codewind.filewatchers.eclipse/src/org/eclipse/codewind/filewatchers/eclipse/CodewindFilewatcherdConnection.java
- dev/org.eclipse.codewind.filewatchers.eclipse/src/org/eclipse/codewind/filewatchers/eclipse/CodewindResourceChangeListener.java
An event with a null resource delta object causes this issue:
https://github.com/eclipse/codewind-eclipse/issues/156
> Issue #156 - Handle resource change events with no resource delta object

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
Fixes #162 
Call dispose on the application to remove logs and anything else related to the application (debug launch, etc.) when a project closed event is received (the application is disabled).
> Issue #162: Remove logs on project closed event

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
Fixes #165 
Remove support for the old style logs/consoles.  Most of this was already removed but there was a bit remaining in the CodewindEclipseApplication class.
> Issue #165: Remove support for old style logs

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/BindProjectAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectWizard.java
Fixed #157 
Improve the error handling if the user tries to create or bind a project while the installer is running.  Also added a message in case the installer fails without an error message.
> Issue #157: Show dialog if user tries to create or bind project while installer running

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Fixes #194 
- Added quick key (A) for Add Existing Project
- Changed quick key for Create New Project to N from P
- Changed quick key for Enable Project and Disable Project to j (both do not show at the same time) to avoid collisions with other menu items
> Issue #194: Fix problems with context menu quick keys

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/CodewindPrefsParentPage.java
Fixes #193 
Change the stop applications preference label to a Text widget so it is accessible.
> Issue #193: Make stop apps preference accessible

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Fixes #191 
The labels in the application overview page should be read only.  Also removed some old commented out code.
> Issue #191: Make application overview labels read only

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallUtil.java
- dev/org.eclipse.codewind.test/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.ui/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind/feature.xml
Fixes #215
- Update the installer to pick up a fix for eclipse/codewind-installer#69
- Update the version of Codewind that gets installed to 0.3
- Update the feature version to 0.3 and the plugin (bundle) versions
For the time being, while the 0.3 version of Codewind is not available, set the **INSTALL_VERSION** environment variable to **latest** before starting Eclipse.  Also make sure to remove any old Codewind images before starting Eclipse.
> Issue #215: Update the installer and the versions

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectSelectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
Fixes #204 
Allow the template table in the new project wizard and the tables in the add project wizard for selecting the type and language to grab excess vertical space.  Also added horizontal and vertical scroll to tables that did not have it.
> Issue #204: Allow tables to resize when the wizard is resized

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
Fixes #248 
The old version would only handle 2 levels such as 0.3.  Fix it to handle multiple levels such as 0.3.0.1.
> Issue #248: Improve the version checking to handle multiple levels

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallUtil.java
Fixes #250 
Accept the CW_TAG env var for setting the Codewind image tag to sync up with Codewind for VSCode.  Continue to allow the INSTALL_VERSION env var as well.
> Issue #250: Accept CW_TAG env var for setting the Codewind image tag

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind/feature.xml
Update the version and default install tag to 0.3.1.  Also include the version checking fix from PR: https://github.com/eclipse/codewind-eclipse/pull/249.
> Issue #254: Update version to 0.3.1 and include version checking fix

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/ProjectLanguage.java
On click of application monitor on a project, goes to the dark-mode monitor to match the performance dashboard.
If the darkmode doesn't exist (i.e the version the metrics dashboard is not recent enough), this will just go to the standard light-mode.
(The same as https://github.com/eclipse/codewind-vscode/pull/188)
Signed-off-by: James Cockbain <james.cockbain@ibm.com>
> add dark mode as default for application monitor

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/UnbindProjectAction.java
Fixes #285 
Don't delete project contents until the projectDeletion event is received.
> Issue #285: Don't delete project contents until projectDeletion event received

- Jenkinsfile
Build date information in 'build_info.properties' would be useful to clarify the correct latest build - the largest build id does not always mean the latest build. 
fixes https://github.com/eclipse/codewind/issues/89
> Add build date information in 'build_info.properties'

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindConnectionActionProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/ManageReposAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
Fixes https://github.com/eclipse/codewind/issues/460
Handle the case where the user has disabled all repositories.  The wizards will show an error and suggest the user click the Manage Repositories link to control the templates/project types shown.  An action has also been added on Projects (Local) to manage repositories.
> CW Issue #460: Handle the case where the user has disabled all repositories

- dev/org.eclipse.codewind.ui/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/ContainerShellAction.java
Fixes #300 
- Use the API for opening a terminal into the application container
- Add the app name to the id so that it shows in the tab name as `Terminal <app name>` instead of just `Terminal`
> Issue #300: Use API for opening terminal and add app name to id

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
The removal of an application may first be detected on an update of the project list, before the projectDeletion event is received.  Clean up the project at this point, including deleting the project contents if it was requested.
This fixes one part of https://github.com/eclipse/codewind/issues/469.  The problem deleting Maven based projects will be addressed in a separate PR.
> CW Issue #469: when app is no longer in project list, perform full delete if requested

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
Fixes #307 
Don't clear out the language when the project type changes if the language is valid for that project type.
> Issue #307: Don't clear out language if project type changed

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CoreUtil.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/util/TestUtil.java
The statement
path = path.replaceAll("\\\\", "/");
will produce a PatternSyntaxException because String.replaceAll()
expects a regex as it's first parameter, and "\\\\" is not a valid regex.
Fix is to change the call to String.replace()
> Fix bug in CoreUtil.getEnvPath()

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallUtil.java
**Problem**
CLI binary name has been changed from codewind-installer -> cwctl. The plugin is pulling the old named binary.
**Solution**
Rename the binary in the plugin code
Signed-off-by: Liam Hampton <liam.hampton@ibm.com>
> Rename binary to cwctl

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindManager.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindObjectFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/HttpUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnectionManager.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/IDEUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindConnectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindConnectionWizard.java
- Common up code in HttpUtil and make sure there is a connect timeout for everything
- Add a progress bar with cancel button to the new connection page when the user clicks Test Connection
- Split out connect code from constructor so can call separately
- Throw exceptions back to the caller so the original exception can be shown to the user
- In order to show the exception with the stack trace, return a multistatus where each line of the stack trace is added as a child status
> Hybrid: Improve connection error handling

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
Improve the error message if project content delete fails because of Maven jobs.  Also removed an unnecessary conversion to File.
> CW Issue #469: Improve the error message if delete fails because of Maven jobs

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectValidationPage.java
Fixes #345 
Add a validation page before the project type selection page.  The validation page shows the detected project type.  The user can Finish on this page or go to the next page to select a different type.
> Issue #345: Add validation page before project type selection page

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectSelectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectValidationPage.java
- Don't clear out the old text if the user cancels the directory browse dialog
- Set the focus on the validation message
> Fix minor UI issues with the add existing project wizard

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RepositoryManagementComposite.java
Fixes https://github.com/eclipse/codewind/issues/664
-  The Manage template sources dialog does not look good on MAC because of the background colour issue in groups for read-only text widgets (used for accessibility reasons). A group is not really needed here since there is just the one table.
-  The details text is not being wrapped on Linux
- The Manage Template Sources action label should have ... at the end
> CW Issue #664: Fix problems with manage template sources dialog on Linux and MAC

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/IDEUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Eclipse IDE PR for https://github.com/eclipse/codewind/issues/649
Hide the CW settings edit and info buttons if the file does not exist.
> CW Issue #649: Hide CW settings button if the file does not exist

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RepositoryManagementComposite.java
Fixes #299 
Add a learn more link to the manage template source dialog.  It opens an external browser since an internal browser would be hidden by the dialog itself.
> Issue #299: Add a learn more link to the manage template sources dialog

- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/Filewatcher.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/CLIState.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/FileChangeEventBatchUtil.java
- dev/org.eclipse.codewind.filewatchers.eclipse/src/org/eclipse/codewind/filewatchers/eclipse/CodewindFilewatcherdConnection.java
- dev/org.eclipse.codewind.filewatchers.standalonenio/src/org/eclipse/codewind/filewatchers/Main.java
In order to support the new Codewind architecture, the Java-based Filewatcherd will now call the cwctl CLI project sync command, instead of POSTing to Turbine.
> Use CWCTL CLI 'project sync' command to build and sync.

- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/CLIState.java
Discovered during automated testing on the other filewatchers: not only is wrapping the path in double quotation marks unnecessary, it is actively harmful on non-Windows platforms.
I've verified that the new version of the code continues to properly handle paths with spaces in them.
> Fix broken, unnecessary path wrapping in CLI process launcher

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/CodewindPrefsParentPage.java
The combo box for selecting a web browser for Node.js debugging does not need 2 labels. The first, longer label will still be read by the screen reader as long as the next widget is the combo box (even if on a separate line) so remove the shorter label.
> CW Issue #723: Remove unnecessary second label for web browser combo

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/InstallUtil.java
Fixes https://github.com/eclipse/codewind/issues/814
The create option needs to be passed in to the cwctl project command for validation to work now.
> CW Issue #814: Pass the create option to cwctl for validation

- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/CLIState.java
Signed-off-by: Jonathan West <jgwest@ca.ibm.com>
> CW Issue #844 - Switch Filewatcherd to use absolute time (not relative time) when calling cwctl project sync

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.base/feature.xml
- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallUtil.java
- dev/org.eclipse.codewind.filewatchers.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.eclipse/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.standalonenio/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.test/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.ui/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind/feature.xml
Fixes #394
Update the plugin and feature versions for 0.6.0. Also update the default Codewind tag.
> Issue #394: Update feature and plugin versions for 0.6.0

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindManager.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnectionManager.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/util/CodewindUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/BindProjectAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RemoveConnectionAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/CodewindConnectionPrefsPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectPage.java
Create the local connection in the CodewindConnectionManager constructor so that it is there before the overview pages get restored.  Also got rid of a duplicate remove method in CodewindConnectionManager.
> CW Issue #1067: Create the local connection in the connection manager constructor

- README.md
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindManager.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnectionManager.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/util/CodewindUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/BindProjectAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RemoveConnectionAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/CodewindConnectionPrefsPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectPage.java
Fixes #https://github.com/eclipse/codewind/issues/1067
Create the local connection in the CodewindConnectionManager so that it is there before the overview pages get restored.  Also deleted a duplicate remove connection method in CodewindConnectionManager.
> CW Issue #1067: Create the local connection in the CodewindConnectionManager

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/ProjectLanguage.java
Add bash to the project languages. Issue https://github.com/eclipse/codewind/issues/1094 opened to improve how project types and languages handled.
> CW Issue #1093: Add bash to the project languages

- README.md
- dev/build.gradle
Add a gradle task to get the dependencies.  This is needed for setting up the development environment.
> Add a getDependencies gradle task

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/UpgradeResult.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/JSONObjectResult.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Updated the code for workspace upgrade to read the JSON result if the exit code is 0 and display it to the user.
> CW Issue #961: show results of workspace migration in a pop up dialog

- dev/org.eclipse.codewind.filewatchers.eclipse/src/org/eclipse/codewind/filewatchers/eclipse/CodewindResourceChangeListener.java
Parent issue: https://github.com/eclipse/codewind/issues/1286
> CW Issue #1286: Filewatcher Eclipse ResourceChangeListener ignores folder deletion events in some cases

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/CodewindConnectionComposite.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/EditConnectionDialog.java
- Improved message so user knows why they need to fill in the password
- Message is long now so set the dialog size to keep it from being the length of the message
- Make sure the OK button is disabled at the start
> CW Issue #839: Improvements to the edit connection dialog

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/IDEUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectValidationPage.java
Fixes #https://github.com/eclipse/codewind/issues/1330
Now that the validation picks up the language, include it in the project validation page.
> CW Issue #1330: Add the language to the project validation page

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
Fixes https://github.com/eclipse/codewind/issues/1348
Pass the JSONObject directly to the socket for authentication instead of converting to a String.
> CW Issue #1348: Pass JSONObject directly for socket authentication

- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.filewatchers.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/FWAuthToken.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/Filewatcher.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/IAuthTokenProvider.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/AuthTokenWrapper.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/HttpGetStatusThread.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/HttpPostOutputQueue.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/HttpUtil.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/WebSocketManagerThread.java
- dev/org.eclipse.codewind.filewatchers.eclipse/src/org/eclipse/codewind/filewatchers/eclipse/CodewindFilewatcherdConnection.java
- dev/org.eclipse.codewind.filewatchers.standalonenio/src/org/eclipse/codewind/filewatchers/Main.java
Parent issue: https://github.com/eclipse/codewind/issues/1309
> CW #1309 - [Filewatcherd] Filewatcher unable to connect to secure PFE (via HTTP/WebSocket) without using an auth token acquired through CWCTL

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectWizard.java
Fixes https://github.com/eclipse/codewind/issues/1393
The create project wizard should not check the install status of Codewind when dealing with a remote connection.
> CW Issue #1393: Don't check install status for remote in create project wizard

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/ProjectType.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorDropAssistant.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
Fixes https://github.com/eclipse/codewind/issues/1392
When dragging and dropping a Codewind style project on to a remote connection that does not have a push registry defined a dialog should pop up to prompt the user to add one, just as it does when the user creates a project or adds an existing project.
Also, when dragging and dropping a project onto a connection, the project overview page should be opened as this is now a new project for that connection.
> CW Issue #1392: Prompt for push registry on drag drop if needed

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorDropAssistant.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectWizard.java
For Codewind style projects on remote connections if there is no push registry, force the user to create one or cancel creation/bind.
> CW Issue #1405: Force the user to either create a push registry or cancel project creation

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
Show an error message if authentication fails for the socket connection.
> CW Issue #1386: Show an error if authentication fails for the socket connection

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/UIConstants.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RegistryManagementComposite.java
- Radio buttons in a table are not accessible so use text instead and add a Set Push button with the other buttons (Add, Remove)
- Changed the name to be Manage Image Registries instead of Manage Container Registries
- Set the learn more link to be https://www.eclipse.org/codewind/dockerregistry.html
- Fixed a bug where if a registry was removed and the user added it back again and did a save it would treat that as a change when it is not
> CW Issue #1479: Remove radio buttons from registry table

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/UIConstants.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RegistryManagementComposite.java
-  Radio buttons in a table are not accessible so use text instead and add a Set Push button with the other buttons (Add, Remove)
- Changed the name to be Manage Image Registries instead of Manage Container Registries
- Set the learn more link to be https://www.eclipse.org/codewind/dockerregistry.html
- Fixed a bug where if a registry was removed and the user added it back again and did a save it would treat that as a change when it is not
> CW Issue #1479: Remove inaccessible radio buttons from registry table

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
Restore the version check for Hybrid now that https://github.com/eclipse/codewind/issues/1455 and https://github.com/eclipse/codewind/issues/1454 are fixed in the runtime.
> CW Issue #1454: restore version check for hybrid

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/CodewindUIPlugin.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/AddConnectionAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/EditConnectionAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RemoveConnectionAction.java
- Use the new cloud connection icon for the new connection context menu item
- Remove the Codewind icon for some menu items (on a cloud connection almost all menu items had this icon)
> CW Issue #1387: Use the new cloud connection icon for the context menu

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CoreUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
Fixes #236
Check the notify flag in the appDetailStatus object and notify the user if true. It pops up a dialog for now but in the future (see https://github.com/eclipse/codewind/issues/655) it could show something like:
```
project1 [Starting][Build successful](Error/Warning hover for details)
```
Though I did notice that the messages are rather long.
> Issue #236: Check notify flag on appDetailStatus and notify user if true

- dev/ant_build/build-cw.xml
- dev/org.eclipse.codewind.base/feature.xml
- dev/org.eclipse.codewind.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.eclipse/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.standalonenio/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.test/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.ui/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind/feature.xml
Fixes https://github.com/eclipse/codewind/issues/1661
Update the versions for the 0.8.0 release.  Updated the third digit since there are only bug fixes going in to this release.
> CW Issue #1661: Update versions for the 0.8.0 release

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/CodewindCorePlugin.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/CLIUtil.java
Update the CLI install location to match the feature version. Need to remember to do this when updating the feature version next time. Looked into doing this automatically but though it is easy to get the version for a plugin, it is not so easy to get the version for a feature. I tried this but it did not work: http://vladdu.blogspot.com/2010/06/retrieving-features-version-number-in.html. It could be a self-hosting thing but then we want it to work when self-hosting.
> Update the CLI install location to default install version

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectWizard.java
The connection is null if the global new codewind project menu item is invoked so need to check for null.  If the connection is null then treat as a local connection (until support is added for choosing a connection).  Checked other calls to isLocal method in the code and they are ok.
> CW Issue #1722: Fix NPE in NewCodewindProjectWizard - need to check for null connection

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/debug/WebBrowserSelectionDialog.java
Use a Label instead of Text so the mnemonic works properly.  Since the label is followed by an entry field it does not need to be a Text widget.
> CW Issue #1731: Fix label for node debug web browser dialog

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
- Fix the Application Endpoint text in the Application Overview page to have the correct background (tested on MAC and Windows)
- Also fixed a type in a message
> CW Issue #732: One more dark mode fix

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindManager.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/CLIUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorLabelProvider.java
Fixes https://github.com/eclipse/codewind/issues/1467
- I did not want to pop up a dialog when there is an error as the user may be working on something else not related to Codewind so I am showing the error message in the status bar. Can make this hover help later (see https://github.com/eclipse/codewind/issues/655).
- Removed some messages that are no longer used
> CW Issue #1467: Improve install status error handling

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindSocket.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/console/SocketConsole.java
- Check that the app is available before sending a disable log stream request
- Separate out dispose() from setEnabled() so not calling dispose on a project closed event (the call to refresh the app will call setEnabled()).
- Put the closing of the output stream in a separate try block to make sure it gets executed
> CW Issue #1398: Don't send log requests if application is disposed

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CoreUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/FileUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/BindProjectAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/CodewindInstall.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorLabelProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectDeployedDialog.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectSelectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectValidationPage.java
- Fix problems where the code is looking up the Codewind application using the Eclipse project name. Use the location instead (project delete, filewatcher, etc.).
- Fix code to use the Eclipse project name when binding an existing project rather than the last segment of the project path.  The last segment of the project path will still be used if the user is binding a project from the file system.
- The problem of creating a project with one name but then specifying a location where the last segment of the path is a different name cannot be fixed because of the limitations of smart import (it does not provide a way to specify a project name). So for this case if the Eclipse project name is different from the Codewind project name then both are shown in the view as: `<Codewind project …
> CW Issue #862: Fix Eclipse project name vs Codewind project name issues

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/JSONObjectResult.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/ProjectTemplateInfo.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/CoreConstants.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Don't try to get the project capabilities or logs until Turbine is ready. Also fixed a problem where it was logging an error that the projectStyle key was missing from the template info (it is never there for Codewind templates).
> CW Issue #1073: Get project capabilities and logs only when Turbine is ready

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ProjectUtil.java
Changes to accompany https://github.com/eclipse/codewind-installer/pull/317 which makes the following changes to the `cwctl project create` command:
- Use `--path`, rather than the first non-flagged argument, as the destination filepath. 
- Splits out the operations on a dir already on disk into a different subcommand to. Currently, this is done by not giving a URL when calling create. This is `cwctl project validate` here, but I think there was confusion about using this before, so happy to discuss and change (or revert to 1 single command, but I think the no URL, if the dir is already there, trick is odd). 
Also, removes `conid` from the arguments of the calls to both commands, as these are both exclusive to a users filesystem and therefore don't need one.
The same changes to the vscode …
> 1452 - Use --path when calling cwctl project create

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
Instead of using "A problem occurred with the ... project" as the title for the app status notify dialog, just use the app name - since it may just be a warning or informational message.
> CW Issue #1732: Just use the project name for the app status notify dialog

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectValidationPage.java
A problem with PR https://github.com/eclipse/codewind-eclipse/pull/516 (looks like conid may be needed on validate after all) showed that after adding null checks for projectInfo I missed one on my own new code. Also fixed a problem where the labels are showing if projectInfo is null and an issue with the validate call where it should be passing in the type id (not the type object).
> CW Issue #1771: Fix missing null check for projectInfo

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ProjectUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/ProjectLanguage.java
Put the conid option back on calls to the cwctl project validate command. Also added the `javascript` language as node.js projects now have this as the language.
> CW Issue #1801: Add the conid option back to cwctl project validate

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/CodewindCorePlugin.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ProjectUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/ProjectLanguage.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/ProjectType.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/CodewindUIPlugin.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/AttachDebuggerAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RestartDebugModeAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorLabelProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectValidationPage.java
Support JavaScript as the new language for node.js projects.
Also cleaned up ProjectLanguage class so it can handle other languages which fixes https://github.com/eclipse/codewind/issues/1094 (ProjectType was already done).
> CW Issue #1809: Support JavaScript as a language

- dev/buildAll.gradle
- dev/org.eclipse.codewind.filewatchers.core/.classpath
- dev/org.eclipse.codewind.filewatchers.core/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.filewatchers.core/build.properties
- dev/org.eclipse.codewind.filewatchers.core/pom.xml
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/Filewatcher.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/WSClientEndpoint.java
- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/internal/WebSocketManagerThread.java
- dev/org.eclipse.codewind.filewatchers.standalonenio/src/org/eclipse/codewind/filewatchers/Main.java
I'm using the exact same versions of the OkHttp dependency as the Codewind Eclipse libraries, so as to avoid any package incompatibilities.
Testing:
- Passes all the standard Filewatcherd automated tests (both the regular and 'chaos engineering' version of these tests).
- Manual testing in Eclipse (local and remote)
- Confirmed it works with both IBM and Oracle JDK (Jetty previously had issues with IBM JDK due to differing TLS/SSL cert names, fortunately not the case here)
Parent issue: https://github.com/eclipse/codewind/issues/1766
> CW Issue #1766:  Replace Jetty WebSocket library with OkHttp WebSocket library

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
Need a null check on typeMap in ProjectTypeSelectionPage.setProjectInfo.  An NPE happens when the user right clicks a project in the Project Explorer view and selects Codewind > Add Project.  Looks like the typeMap is not initialized when setProjectInfo is called in this case.  The projectTypeInfo and projectSubtypeInfo will still get initialized in this case because updateTables is called right after typeMap is initialized.
Also opened this issue to clean up this class because the overloading of the language and subtype concepts makes the code complicated and confusing: https://github.com/eclipse/codewind/issues/1833.
> CW Issue #1771: Missing null check on typeMap

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorLabelProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/CodewindConnectionComposite.java
Fixes https://github.com/eclipse/codewind/issues/1861
- Show the swift icon for projects with language set to swift
- Add space between the entry fields and the learn more link in the new connection composite
- Common up the code in CodewindApplication for calculating the app base url
> CW Issue #1861: Show swift icon for projects of that language

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ProjectUtil.java
Add the conid option back to the project create call. It was removed for https://github.com/eclipse/codewind-eclipse/pull/516 but it is needed since create sometimes calls validate - see https://github.com/eclipse/codewind/issues/1829.
> CW Issue 1805: Add conid option back on project create command

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/ProcessHelper.java
Signed-off-by: Matthew Colegate <colegate@uk.ibm.com>
Fixes https://github.com/eclipse/codewind/issues/1765
This change ensures that all Strings obtained from cwctl are encoded as UTF-8 strings rather than whatever the system default is.
This change affects all interactions between the Eclipse Plugin and CWCTL. **Extensive Testing Required!**
@eharris369 Would you be so kind as to test and review please.
> Ensure UTF-8 encoding on strings received from cwctl

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RegistryManagementComposite.java
Fixes https://github.com/eclipse/codewind/issues/1905
- Change the button from `Set Push` to `Set as Push`
- For the push registry show `Set` in the column and blank for non-push registries
> CW Issue #1905: Improve the manage image registries dialog

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RegistryManagementComposite.java
Fixes https://github.com/eclipse/codewind/issues/1907
Instead of a simple text box for the image registry address, use a combo with a list of common registries.  The user is still able to type in their own registry.
> CW Issue #1907: add image registry dialog include drop down of common registries

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/console/CodewindConsoleFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/console/SocketConsole.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/HideAllLogsAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/LogFileAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/ShowAllLogsAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Fixes https://github.com/eclipse/codewind/issues/1934
Change all of the log file actions to run inside jobs so they don't hold up the IDE.
> CW Issue #1934: Run all log file actions in jobs

- dev/org.eclipse.codewind.filewatchers.core/src/org/eclipse/codewind/filewatchers/core/Filewatcher.java
Parent issue: https://github.com/eclipse/codewind/issues/1952
> CW Issue #1952 - Java Filewatcher is not correctly rate limiting its PUT requests on failure #1952

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RegistryManagementComposite.java
If the user has selected to remove the push registry then it also needs to be deregistered as the image push registry using the new DELETE api/v1/imagepushregistry endpoint.
> CW Issue #1746: derigister as push if push registry is removed

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
Signed-off-by: Matthew Colegate <colegate@uk.ibm.com>
This PR fixes the front end for eclipse/codewind#1509 in Eclipse.
OpenLiberty projects are currently defined as type Docker with language Java. I've raised eclipse/codewind#1960 to try and improve that.
Please feel free to comment on anything I've missed!
> Enable metrics injection for Docker Java projects

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Remove DESCRIPTION style so that the extra space for it after the section title does not get created.
> CW Issue #1698: Remove extra space after sections in app overview page

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/BindAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/BindProjectAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorLabelProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ConnectionSelectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectSelectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectValidationPage.java
If the Codewind > Add Project context menu item is used on a project the user should be able to select the connection they want if there is more than one.
- Added a connection selection page to the start of the wizard if there is more than one connection
- Moved the install status checking to BindProjectWizard so it can be done after the user selects the connection
- Added code to check if the remote connection is connected and if not connect when the user clicks next
- Verified that the new connection selection page is accessible
> CW Issue #1695: Allow the user to select the connection when binding a project

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Fixes https://github.com/eclipse/codewind/issues/1698
- Fixed a problem where some entries were hidden if the application is disabled instead of showing a value of "Not available"
- Created entries in the Messages files for a couple of labels
> CW Issue #1698: Cleanup items for application overview page

- Jenkinsfile
Update the appsody release to 0.5.7.  See https://github.com/eclipse/codewind/issues/1931.
> CW Issue #1931: Update the appsody release to 0.5.7

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/UIConstants.java
Fixes https://github.com/eclipse/codewind/issues/2033
The documentation has been re-organized so the links in the IDE need to be updated.  See https://github.com/eclipse/codewind/issues/2033 for more information.
> CW Issue #2033: Update links to documentation

- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/util/CodewindUtil.java
Fixes #571 
- Node projects need to restart when auto build mode is changed in order to turn on/off nodemon so need to make sure the application has finished restarting before trying to ping it
- Created a more generic method for app status testing
> Issue #571: Check application status after changing auto build mode

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/EnableDisableInjectMetricsAction.java
If the application already has embedded metrics then there is no need to show the inject metrics action.  If the application has injected metrics then the action should still show so the user has the option to remove it.
> CW Issue #1710: Hide inject metrics action if app has embedded metrics

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/EnableDisableInjectMetricsAction.java
If the application already has embedded metrics then there is no need to show the inject metrics action. If the application has injected metrics then the action should still show so the user has the option to remove it.
> CW Issue #1710: Hide inject metrics action if app has embedded metrics (0.9.0)

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/UIConstants.java
Fixes https://github.com/eclipse/codewind/issues/2187
The project settings doc link has changed after the restructuring of the docs.
> CW Issue #2187: Fix project settings doc link

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/InstallUtil.java
The remove command for removing Codewind images has been changed so the code in the IDE needs to be updated accordingly.  See https://github.com/eclipse/codewind-installer/pull/377 for details.
> CW Issue #2079: Update for remove command changes

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/AttachDebuggerAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RestartDebugModeAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Fixes https://github.com/eclipse/codewind/issues/1252
Show the restart in debug mode action if the capabilities support it even if a debug session cannot be set up automatically for the user.  Show the user a dialog telling them they need to attach a debugger manually and give them the option to cancel along with the option to be notified when the debug port becomes available (on by default).
> CW Issue #1252: Show restart in debug mode if capabilities support it

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
Fixes #319 
If there is only one project type available then select it.  Also fixed a missing null check.
> Issue #319: Select the project type if there is only one

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenPerfMonitorAction.java
The ping test is no longer needed for the performance dashboard action.
> CW Issue #2299: remove ping test from open perf dashboard

- Jenkinsfile
- dev/org.eclipse.codewind.filewatchers.standalonenio/run_fwd_tests_if_needed.sh
- dev/org.eclipse.codewind.filewatchers.standalonenio/src/org/eclipse/codewind/filewatchers/Main.java
Add the filewatcher tests to the PR build, but ensure that the tests only run if a file changed under one of the `org.eclipse.codewind.filewatchers.*` projects. This should prevent the tests from running for non-filewatcher PRs.
Parent issue: https://github.com/eclipse/codewind/issues/2327
> CW Issue #2327 - Add Filewatcher automated tests to FWd PR builds

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/IDEUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RepositoryManagementComposite.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectValidationPage.java
Fixes #2336
Copy FontData instead of overwriting it when creating a new font based on an existing font.
> CW Issue #2336: Copy FontData instead of overwriting when creating fonts

- dev/org.eclipse.codewind.core/about.properties
Fixes https://github.com/eclipse/codewind/issues/2339
Update the copyright and link in the branding file (about.properties).
> CW Issue #2339: Update copyright and link in about.properties

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RepositoryManagementComposite.java
Fixes https://github.com/eclipse/codewind/issues/2353
Allow multiple selection in the manage template sources table so users can select more then one non-default template source and click Remove.
> CW Issue #2353: Allow multiple selection in the template sources table

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/AddConnectionAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Fixes https://github.com/eclipse/codewind/issues/2355
The new connection menu item should have a mnemonic for accessibility support.
> CW Issue #2355: Add mnemonic for the new connection menu item

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnectionManager.java
Fixes https://github.com/eclipse/codewind/issues/2433
Fix NPE on Eclipse shutdown when ConnectionManager not initialized.
> CW Issue #2433: Fix NPE on shutdown when ConnectionManager not initialized

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
Fixes https://github.com/eclipse/codewind/issues/2426
Add the host and port to the debug target name. They were already being passed to NLS.bind so just needed to fix the message.
> CW Issue #2426: Add the host and port to the debug target name

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindManager.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/connection/CodewindConnection.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Fixes https://github.com/eclipse/codewind/issues/2424
Show the connection unavailable message in the application overview page if the connection is lost. This is the same as what shows when Eclipse is first started for any application overview pages until the connections are re-established.
Also changed some calls to CoreUtil.updateAll to CoreUtil.updateConnection. These probably date back to when there was only one connection. The only time updateAll needs to be called now is when a connection is added.
> CW Issue #2424: Show connection unavailable msg in app overview page if connection lost

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/ContainerShellAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
When opening the container shell, checks for the terminal service bundles. If they are not installed then an error dialog is shown to the user asking them to check that they are using the Eclipse IDE for Java Enterprise Java Developers.
https://github.com/eclipse/codewind/issues/2309
No
No
> CW Issue #2309: Check for terminal service bundles before opening container shell

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/IDEUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/WelcomePageEditorPart.java
Fixes up the read only text background for dark mode on Windows.
https://github.com/eclipse/codewind/issues/2529
No
Tried to find a more static method of doing this but every time I scrolled it went back to the wrong background so added a PaintListener.
Tested on Windows including high contrast mode and on Linux. Don't have access to a MAC machine right now.
> CW Issue #2529: Fix the read only text background for Windows dark mode

- dev/org.eclipse.codewind.ui/plugin.xml
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/CodewindUIPlugin.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RegistryManagementComposite.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/RepositoryManagementComposite.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/CodewindConnectionComposite.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ConnectionSelectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/LogLevelSelectionDialog.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindConnectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectDeployedDialog.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectSelectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectTypeSelectionPage.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectValidationPage.java
- dev/org.eclipse.codewind.ui/xml/CodewindUIContexts.xml
It creates a very general context help page with a link to open the Codewind Documentation and adds it to all dialogs and wizards. It also makes sure there is a widget in focus on all dialog and wizard pages since the context help does not work otherwise (this needed fixing anyway).
https://github.com/eclipse/codewind/issues/773
No
No
> CW Issue #773: Add generic Codewind help to dialogs and wizards

- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AppsodyJavaMicroprofileAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AppsodyJavaSpringAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/AppsodyNodeExpressAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseAppsodyAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseDebugTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/BaseValidationTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/NodeAutoBuildTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/NodeValidationTest.java
- dev/org.eclipse.codewind.test/src/org/eclipse/codewind/test/util/CodewindUtil.java
- Makes the base test case more flexible so that tests can have more than one connection and/or application.
- Cleaned up the Appsody tests to not check for build states.
https://github.com/eclipse/codewind/issues/2577
No
No
> CW Issue #2577: Make the base test case more flexible

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/ProjectUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorDropAssistant.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectWizard.java
Attempts to clean up if project create or bind times out or is canceled.
https://github.com/eclipse/codewind/issues/2601
No
No
> CW Issue #2601: Cleanup if create or bind project times out 0.11.0

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/GetStartedAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenWelcomePageAction.java
- Opens the editor first so the view does not take up the entire window. Sets the editor as the active part after opening the view.
- Makes sure the J2EE perspective is open (in case the user was in a different perspective before installing Codewind)
https://github.com/eclipse/codewind/issues/2675
No
No
> CW Issue #2675: Open editor first so view does not take up entire window - 0.11.0

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/GetStartedAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/OpenWelcomePageAction.java
- Opens the editor first so the view does not take up the entire window. Sets the editor as the active part after opening the view.
- Makes sure the J2EE perspective is open (in case the user was in a different perspective before installing Codewind)
https://github.com/eclipse/codewind/issues/2675
No
No
> CW Issue #2675: Open editor first so view does not take up entire window

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectSelectionPage.java
Fixes a problem with the radio button behaviour in the project selection page. If the user chose to select a project from the file system and used the browse button to select the project folder, the radio button would switch back to selecting the project from the workspace.
https://github.com/eclipse/codewind/issues/2704
No
No
> CW Issue #2704: Fix radio button problem with project selection page

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/KubeUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/RemoteEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/launch/CodewindLaunchConfigDelegate.java
- Don't clear out the launches on terminate so that the user can still look at the console for the launch in case there is a problem
- Don't show the timeout message dialog if the user canceled the debug connect
- Also fixed an NPE in port forward logging
https://github.com/eclipse/codewind/issues/2790
No
No
> CW Issue #2790: Fix various issues with debug

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/launch/CodewindDebugConnector.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/launch/CodewindLaunchConfigDelegate.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/launch/UtilityLaunchConfigDelegate.java
- Fixes the code to not multiply the debug attach timeout by 1000
- Increases the default timeout so users don't suddenly get timeouts when they didn't before
- Some exceptions were being ignored so changed the code to pass the exception on
- Fixes the UtilityLaunchConfigDelegate to extend LaunchConfigurationDelegate  instead of the Java launch delegate
https://github.com/eclipse/codewind/issues/2813
No
No
> CW Issue #2813: Fix debug connect timeout and debug error handling

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/CLIUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/cli/OtherUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/launch/UtilityLaunchConfigDelegate.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/IDEUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/DiagnosticsAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/LocalConnectionActionProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/RemoteConnectionActionProvider.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/DiagnosticsDialog.java
Adds an action to collect Codewind diagnostics. This action is only available if support features are enabled in the preferences. When the action is invoked a dialog pops up to allow the user to choose what to include in the diagnostics. A launch is created for generating the diagnostics and the console view is opened so the user can see the output.
https://github.com/eclipse/codewind/issues/2851
Yes
No
> CW Issue #1579/2851: Add a collect diagnostics action

- dev/org.eclipse.codewind.core/plugin.properties
- dev/org.eclipse.codewind.core/plugin.xml
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/KubeUtil.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/RemoteEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/launch/CodewindDebugConnector.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/launch/CodewindLaunchConfigDelegate.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/launch/RemoteLaunchConfigDelegate.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/plugin.xml
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/debug/NodeJSDebugLauncher.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Fixes the remote debug relaunch problem by including the port forward setup in the launch.
https://github.com/eclipse/codewind/issues/2885
Yes - there is no longer a separate port forward launch in the Java case. Instead it is a second process in the debug launch. For Node.js projects there is still a port forward launch.
No
> CW Issue #2885: Fix the remote debug relaunch

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Makes sure that the application overview page is not disposed before trying to update it.
https://github.com/eclipse/codewind/issues/2917
No
No
> CW Issue #2917: Check if the overview page is disposed before updating

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindApplicationFactory.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/RemoteEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/constants/DetailedAppStatus.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/plugin.xml
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorLabelProvider.java
- Provides detailed status to user through tooltip in the Codewind Explorer view
- Adds the detailed app status and build status to the Project Overview page
https://github.com/eclipse/codewind/issues/655
Yes - The tooltip support in common viewers was added to Eclipse 4.12 (2019-06) so 4.11 (2019-03) is not supported anymore.
No
> CW Issue #655: Use tooltip to provide detailed status to user

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/ProjectDeployedDialog.java
Improve the usability of the project deployed dialog.
https://github.com/eclipse/codewind/issues/2924
No
I could use a table with a Connection column and an Action column. The Connection column would show the names of connections where the project is already deployed. The Action column would show which action to take for each connection (Remove, Disable, Maintain). There would be buttons for users to change the action on the selected connections (outside the table since buttons or dropdowns in a table are not accessible). I think this would be overkill though since most users won't even see this dialog and those that do will only have the project deployed on one other connection.
> CW Issue #2924: Project deployed dialog usability improvements

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CoreUtil.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorDropAssistant.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/BindProjectWizard.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/wizards/NewCodewindProjectWizard.java
Adds a link to the image registry documentation on the missing push registry dialog that pops up for Codewind style projects.
https://github.com/eclipse/codewind/issues/2992
No
No
> CW Issue #2992: Add link to documentation on push registry dialogs

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/ManageRegistriesAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/ManageReposAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
Displays a progress monitor while retrieving existing template source or image registry data needed to open the manage template sources or manage image registries dialog. With the progress monitor there will be no unexplained delay between when the user clicks the action and when they see the dialog.
https://github.com/eclipse/codewind/issues/2997
No
No
> CW Issue #2997: Show progress monitor while retreiving data needed to open dialog

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/CodewindCorePlugin.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/IDebugLauncher.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/launch/RemoteLaunchConfigDelegate.java
- dev/org.eclipse.codewind.ui/META-INF/MANIFEST.MF
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/actions/AttachDebuggerAction.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/debug/NodeJSDebugLauncher.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/Messages.java
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/messages/messages.properties
- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/CodewindPrefsParentPage.java
Use the Eclipse builtin node.js debugger if available. Otherwise use the external Chrome based browser as before.
https://github.com/eclipse/codewind/issues/2975
Yes
No
> CW Issue #2975: Use Eclipse builtin node.js debugger if available

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/CodewindPrefsParentPage.java
#523  What type of PR is this ? 
Adds a null check for useBuiltinDebugButton in performOk.
https://github.com/eclipse/codewind/issues/3022
No
No
> CW Issue #3022: Add missing null check for useBuiltinDebugButton in preferences

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/views/CodewindNavigatorLabelProvider.java
Disables the indicator on the project if the message severity is INFO. The hover help will still be there. Also got rid of some duplicate code for the hover help and the description text.
https://github.com/eclipse/codewind/issues/3024
No
No
> CW Issue #3024: Don't show indicator for project details with INFO severity

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Clear the logs link text when there are no logs available so that JAWS does not read the old link text along with the "No logs available" text.
https://github.com/eclipse/codewind/issues/3045
No
No
> CW Issue #3045: Clear logs link text when no logs available

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Clear the logs link text when there are no logs available so that JAWS does not read the old link text along with the "No logs available" text.
https://github.com/eclipse/codewind/issues/3045
No
No
> CW Issue #3045: Clear logs link text when no logs available 0.13.0

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Fix the background for the project logs links in the project overview page so that it matches the overall background for the page when using dark mode.
https://github.com/eclipse/codewind/issues/3061
No
No
> CW Issue #3061: Fix background for log links in project overview

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Fix the background for the project logs links in the project overview page so that it matches the overall background for the page when using dark mode.
https://github.com/eclipse/codewind/issues/3061
No
No
> CW Issue #3061: Fix background for log links in project overview 0.13.0

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Positions the labels in the project overview page at the beginning. Still looking for a fix to the scrollbar problem so it will be in a separate PR.
https://github.com/eclipse/codewind/issues/3081
No
No
> CW Issue #3081: Position the project overview labels at beginning 0.13.0

- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/CodewindEclipseApplication.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/launch/CodewindDebugConnector.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/launch/CodewindLaunchConfigDelegate.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/Messages.java
- dev/org.eclipse.codewind.core/src/org/eclipse/codewind/core/internal/messages/messages.properties
Works around the problem of the projectRestartResult event coming too soon for appsody projects, before the debug port is ready (see https://github.com/eclipse/codewind/issues/239) by:
- increasing the debug timeout
- checking for the specific exception that occurs when the debug port is not ready and showing a timeout message in this case (the exception is also shown)
https://github.com/eclipse/codewind/issues/3119
No
No
> CW Issue #3119: Better detection and message for debug attach timeout

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/editors/ApplicationOverviewEditorPart.java
Stop changing the background colour for table labels in the application overview page as it causes problems with high contrast mode.
https://github.com/eclipse/codewind/issues/3163
No
No
> CW Issue #3162: fix app overview table labels in high contrast

- dev/org.eclipse.codewind.ui/src/org/eclipse/codewind/ui/internal/prefs/LinkManagementComposite.java
Fixes the missing border on the add project link dialog environment variable field.
https://github.com/eclipse/codewind/issues/3167
No
No
> CW Issue #3167: Fix missing border on project link env var field
